openapi: 3.2.0
info:
  title: Projects Project API
  description: 'PEXA Projects External Client API for Projects <br> <br> This API uses the OAuth 2.0 protocol for authentication and authorization. It supports the following OAuth 2.0 flows: <br> - Client Credentials <br> - Authorization Code <br> <br> Scopes are used to grant an application different levels of access to data. Each API endpoint will require specific scopes. <br> The scopes are listed against each API endpoint. <br> <br> For more information, see the following guides: <br> - [Authentication](../../../Exchange/docs/documentation/)

    '
  version: v4
  x-api-version: 4.0.0
  contact:
    name: PEXA Projects
    email: pexaprojects-prdsupport@pexa.com.au
  x-pexa-products:
  - pexa-projects
servers:
- url: '{{ service.url }}'
tags:
- name: Project
paths:
  /v4/projects:
    post:
      operationId: createProject
      security:
      - oauth2:
        - au:projects:project:write
      summary: Create Project
      description: Create a new project <br> Scopes:<br><i>au:projects:project:write</i>
      tags:
      - Project
      parameters:
      - $ref: '#/components/parameters/RequestCorrelationIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
            examples:
              NSW:
                $ref: '#/components/examples/NswProjectRequest'
              VIC:
                $ref: '#/components/examples/VicProjectRequest'
              QLD:
                $ref: '#/components/examples/QldProjectRequest'
              SA:
                $ref: '#/components/examples/SaProjectRequest'
      responses:
        '201':
          description: Successfully created a project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
              examples:
                NSW:
                  $ref: '#/components/examples/NswProjectResponse'
                VIC:
                  $ref: '#/components/examples/VicProjectResponse'
                QLD:
                  $ref: '#/components/examples/QldProjectResponse'
                SA:
                  $ref: '#/components/examples/SaProjectResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /v4/projects/{projectId}:
    put:
      operationId: updateProject
      security:
      - oauth2:
        - au:projects:project:write
      summary: Update Project
      description: Update an existing project <br> Scopes:<br><i>au:projects:project:write</i>
      tags:
      - Project
      parameters:
      - $ref: '#/components/parameters/RequestCorrelationIdHeader'
      - name: projectId
        in: path
        required: true
        description: Id of the project to update
        example: 1234
        schema:
          type: integer
          format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
            examples:
              NSW:
                $ref: '#/components/examples/NswProjectRequest'
              VIC:
                $ref: '#/components/examples/VicProjectRequest'
              QLD:
                $ref: '#/components/examples/QldProjectRequest'
              SA:
                $ref: '#/components/examples/SaProjectRequest'
      responses:
        '200':
          description: Successfully updated a project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
              examples:
                NSW:
                  $ref: '#/components/examples/NswProjectResponse'
                VIC:
                  $ref: '#/components/examples/VicProjectResponse'
                QLD:
                  $ref: '#/components/examples/QldProjectResponse'
                SA:
                  $ref: '#/components/examples/SaProjectResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /v4/projects/{projectId}/statuses:
    get:
      operationId: statuses
      security:
      - oauth2:
        - au:projects:status:read
      tags:
      - Project
      description: Fetch the status details for a project <br> Scopes:<br><i>au:projects:status:read</i>
      parameters:
      - $ref: '#/components/parameters/RequestCorrelationIdHeader'
      - name: projectId
        in: path
        required: true
        description: Id of the project to find status details for
        example: 1234
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Status details for a project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectStatus'
              examples:
                Status:
                  $ref: '#/components/examples/ProjectStatusResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /v4/projects/{projectId}/workspaces:
    get:
      operationId: workspaces
      security:
      - oauth2:
        - au:projects:workspaces:read
      tags:
      - Project
      description: Fetch the list of workspaces of a project <br> Scopes:<br><i>au:projects:workspaces:read</i>
      parameters:
      - $ref: '#/components/parameters/RequestCorrelationIdHeader'
      - name: projectId
        in: path
        required: true
        description: Id of the project to list workspaces for
        example: 1234
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: The list of workspaces of a project
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectsWorkspace'
              examples:
                ListOfOne:
                  $ref: '#/components/examples/WorkspacesResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  examples:
    SaProjectRequest:
      summary: Example for SA/ACT/WA/TAS
      value:
        projectName: ABC Project
        jurisdiction: SA
        workgroupId: 1000
        estimatedSettlementDate: JUN 2028
        parentTitle: 13/12322
        proprietorOnTitle:
        - John Smith
        - Adam Smith
        supplierApplicable: true
        supplierDetails:
          name: ' XHJ corp LTD'
          phone: '6125548555'
          abn: '12345678912'
          addressLine1: L1 Tower 2
          addressLine2: 727 Collins St
          suburb: Docklands
          postcode: '3000'
          state: SA
          email: sv@test.com
        withMortgageeOnTitles: true
        mortgageeOnTitles:
        - subscriberName: NECDL EASTPAC
          subscriberId: '1234'
          dealingNumber: ABC1234
          participantName: CABRAMATTA conveyancing
        intentionToLock: true
        projectStages: false
        settlementRestriction: true
    WorkspacesResponse:
      summary: An example of the workspaces response
      value:
      - workspaceId: PEXA165111203
        subscriberReference: CJD:121330
        unregisteredLotNumbers:
        - '2'
        childTitles:
        - '51272439'
        participantRepresentativeData:
          mortgageeOnTitleReps:
          - Curell Partner
          - Corrigan Legal
          incomingMortgageeReps:
          - MSA National
          incomingProprietorReps:
          - Empire Legal
        partyData:
          proprietorsOnTitle:
          - Kangaroo Pty LTd
          - SMV Consulting
          incomingProprietors:
          - Maria Georgious
        lodgementStatus: Completed
        settlementStatus: Disbursed
        settlementDate: 2022-01-02
        settlementDateAcceptance:
          status: PARTIALLY_ACCEPTED
          statusDetails:
            acceptanceByMortgageeOnTitleReps: PENDING
            acceptanceByIncomingMortgageeReps: ACCEPTED
            acceptanceByIncomingProprietorReps: ACCEPTED
        financialData:
          gstWithholdingStatus: MATCHING
          grossConsideration: $2,044,000.00
          vendorFunds: $1,251,222.11
          payoutAmount: $230,152.00
          balanced: true
    QldProjectRequest:
      summary: Example for QLD
      value:
        projectName: ABC Project
        jurisdiction: QLD
        workgroupId: 1000
        estimatedSettlementDate: JUN 2028
        parentTitle: 13/12322
        proprietorOnTitle:
        - John Smith
        - Adam Smith
        supplierApplicable: true
        supplierDetails:
          name: XHJ corp LTD
          phone: '6125548555'
          abn: '12345678912'
          addressLine1: L1 Tower 2
          addressLine2: 727 Collins St
          suburb: Docklands
          postcode: '3000'
          state: QLD
          email: sv@test.com
        withMortgageeOnTitles: true
        mortgageeOnTitles:
        - subscriberName: NECDL EASTPAC
          subscriberId: '1234'
          dealingNumber: ABC1234
          participantName: CABRAMATTA conveyancing
        intentionToLock: true
        projectStages: false
        settlementRestriction: true
        qldPropertyDetails:
          currentLandUse: Dwelling
          marginScheme: false
          safetySwitch:
            installed: true
            informed: false
          smokeAlarm:
            installed: true
            informed: true
    VicProjectResponse:
      summary: Example for VIC
      value:
        id: 1234
        projectName: ABC Project
        jurisdiction: VIC
        workgroupId: 1000
        estimatedSettlementDate: JUN 2028
        parentTitle: 13/12322
        proprietorOnTitle:
        - John Smith
        - Adam Smith
        supplierApplicable: true
        supplierDetails:
          name: XHJ corp LTD
          phone: '6125548555'
          abn: '12345678912'
          addressLine1: L1 Tower 2
          addressLine2: 727 Collins St
          suburb: Docklands
          postcode: '3000'
          state: VIC
          email: sv@test.com
        withMortgageeOnTitles: true
        mortgageeOnTitles:
        - subscriberName: NECDL EASTPAC
          subscriberId: '1234'
          dealingNumber: ABC1234
          participantName: CABRAMATTA conveyancing
        intentionToLock: true
        projectStages: false
        settlementRestriction: true
        projectStatus: ARCHIVED
        historicalParentTitles:
        - 22/54321
        workspacesCreated: true
        vicPropertyDetails:
          restrictiveCovenant: true
          covenantMcpRef: '123123123'
          covenantMcpExpiryDate: '2022-11-30'
          municipalityName: Baw Baw Shire Council
          natureOfProperty: Residential
          primaryLandUse: Dwelling
          primaryConstructionType: Timber
    SaProjectResponse:
      summary: Example for SA/ACT/WA/TAS
      value:
        id: 1234
        projectName: ABC Project
        jurisdiction: SA
        workgroupId: 1000
        estimatedSettlementDate: JUN 2028
        parentTitle: 13/12322
        proprietorOnTitle:
        - John Smith
        - Adam Smith
        supplierApplicable: true
        supplierDetails:
          name: ' XHJ corp LTD'
          phone: '6125548555'
          abn: '12345678912'
          addressLine1: L1 Tower 2
          addressLine2: 727 Collins St
          suburb: Docklands
          postcode: '3000'
          state: SA
          email: sv@test.com
        withMortgageeOnTitles: true
        mortgageeOnTitles:
        - subscriberName: NECDL EASTPAC
          subscriberId: '1234'
          dealingNumber: ABC1234
          participantName: CABRAMATTA conveyancing
        intentionToLock: true
        projectStages: false
        settlementRestriction: true
        projectStatus: ACTIVE
        historicalParentTitles:
        - 98/12345
        workspacesCreated: false
    QldProjectResponse:
      summary: Example for VIC
      value:
        id: 1234
        projectName: ABC Project
        jurisdiction: QLD
        workgroupId: 1000
        estimatedSettlementDate: JUN 2028
        parentTitle: 13/12322
        proprietorOnTitle:
        - John Smith
        - Adam Smith
        gstApplicable: true
        supplierApplicable: true
        supplierDetails:
          name: XHJ corp LTD
          phone: '6125548555'
          abn: '12345678912'
          addressLine1: L1 Tower 2
          addressLine2: 727 Collins St
          suburb: Docklands
          postcode: '3000'
          state: QLD
          email: sv@test.com
        withMortgageeOnTitles: true
        mortgageeOnTitles:
        - subscriberName: NECDL EASTPAC
          subscriberId: '1234'
          dealingNumber: ABC1234
          participantName: CABRAMATTA conveyancing
        intentionToLock: true
        projectStages: false
        settlementRestriction: true
        projectStatus: DELETED
        historicalParentTitles:
        - 55/98765
        workspacesCreated: true
        qldPropertyDetails:
          currentLandUse: Dwelling
          marginScheme: false
          safetySwitch:
            installed: true
            informed: false
          smokeAlarm:
            installed: true
            informed: true
    ProjectStatusResponse:
      summary: Example of a status response
      value:
        proprietorOnTitles:
        - ABC LTD
        - XYZ LTD
        parentTitle: 20/1185379
        mortgageeNames:
        - John X
        - Robertson Y
        estimatedSettlementDate: JAN 2024
        jurisdiction: NSW
        invitationAcceptance:
          incomingMortgagee:
            accepted: 2
            pending: 1
            declined: 1
            notInvited: 0
          mortgageeOnTitle:
            accepted: 44
            pending: 22
            declined: 0
            notInvited: 0
          incomingProprietor:
            accepted: 44
            pending: 22
            declined: 0
            notInvited: 0
        settlementDateAcceptance:
          incomingMortgagee:
            accepted: 1
            pending: 1
          mortgageeOnTitle:
            accepted: 22
            pending: 11
          incomingProprietor:
            accepted: 23
            pending: 10
        workspaceStatus:
          allActive: 1
          settlingToday: 0
          completed: 0
          withdrawn: 0
          all: 1
          awaitingDigitalSignature: 0
    VicProjectRequest:
      summary: Example for VIC
      value:
        projectName: ABC Project
        jurisdiction: VIC
        workgroupId: 1000
        estimatedSettlementDate: JUN 2028
        parentTitle: 13/12322
        proprietorOnTitle:
        - John Smith
        - Adam Smith
        supplierApplicable: true
        supplierDetails:
          name: XHJ corp LTD
          phone: '6125548555'
          abn: '12345678912'
          addressLine1: L1 Tower 2
          addressLine2: 727 Collins St
          suburb: Docklands
          postcode: '3000'
          state: VIC
          email: sv@test.com
        withMortgageeOnTitles: true
        mortgageeOnTitles:
        - subscriberName: NECDL EASTPAC
          subscriberId: '1234'
          dealingNumber: ABC1234
          participantName: CABRAMATTA conveyancing
        intentionToLock: true
        projectStages: false
        settlementRestriction: true
        vicPropertyDetails:
          restrictiveCovenant: true
          covenantMcpRef: '123123123'
          covenantMcpExpiryDate: '2022-11-30'
          municipalityName: Baw Baw Shire Council
          natureOfProperty: Residential
          primaryLandUse: Dwelling
          primaryConstructionType: Timber
    NswProjectRequest:
      summary: Example for NSW
      value:
        projectName: ABC Project
        jurisdiction: NSW
        workgroupId: 1000
        estimatedSettlementDate: JUN 2028
        parentTitle: 13/12322
        proprietorOnTitle:
        - John Smith
        - Adam Smith
        supplierApplicable: true
        supplierDetails:
          name: XHJ corp LTD
          phone: '6125548555'
          abn: '12345678912'
          addressLine1: L1 Tower 2
          addressLine2: 727 Collins St
          suburb: Docklands
          postcode: '3000'
          state: NSW
          email: sv@test.com
        withMortgageeOnTitles: true
        mortgageeOnTitles:
        - subscriberName: NECDL EASTPAC
          subscriberId: '1234'
          dealingNumber: ABC1234
          participantName: CABRAMATTA conveyancing
        intentionToLock: true
        projectStages: false
        settlementRestriction: true
        nswPropertyDetails:
          locality: Carey Estate2
          natureOfProperty: Vacant land
    NswProjectResponse:
      summary: Example for NSW
      value:
        id: 1234
        projectName: ABC Project
        jurisdiction: NSW
        workgroupId: 1000
        estimatedSettlementDate: JUN 2028
        parentTitle: 13/12322
        proprietorOnTitle:
        - John Smith
        - Adam Smith
        supplierApplicable: true
        supplierDetails:
          name: XHJ corp LTD
          phone: '6125548555'
          abn: '12345678912'
          addressLine1: L1 Tower 2
          addressLine2: 727 Collins St
          suburb: Docklands
          postcode: '3000'
          state: NSW
          email: sv@test.com
        withMortgageeOnTitles: true
        mortgageeOnTitles:
        - subscriberName: NECDL EASTPAC
          subscriberId: '1234'
          dealingNumber: ABC1234
          participantName: CABRAMATTA conveyancing
        intentionToLock: true
        projectStages: false
        settlementRestriction: true
        projectStatus: ACTIVE
        historicalParentTitles:
        - 13/12345
        workspacesCreated: true
        nswPropertyDetails:
          locality: Carey Estate2
          natureOfProperty: Vacant land
  schemas:
    NswPropertyDetails:
      type: object
      description: Property details for the NSW jurisdiction
      properties:
        locality:
          description: The name assigned to a government administrative district, such as a Parish, County or Local Government Area.
          type: string
        natureOfProperty:
          type: string
          description: Specify the use of the property being dealt with
          pattern: Carspace|Commercial|Factory|Marine berth|Office|Residence|Shop|Vacant land|Warehouse
    GstWithholdingStatus:
      type: string
      description: 'The status of GST withholding. Can be one of the following: * MATCHING - Form one lodged via PEXA and GST line item created * MANUAL - Form one not lodged via PEXA but GST line item created * NOT_LODGED - Form one not lodged via PEXA and no GST line item created * MISMATCH - Incorrect PRN and/or GST amount entered

        '
      format: string
    MotParticipants:
      type: object
      description: Details on incoming mortgagees
      required:
      - participantName
      - subscriberName
      - subscriberId
      properties:
        dealingNumber:
          type: string
          description: It is the Land Registry document number. This number is supplied by your land registry and can be used as your reference in any further communications with the Registry. Numbers begins with 2 or 3 letters following by a number. The letters identify the county in which the property is situate, e.g. VIC52825 denotes a property in Victoria
        participantName:
          description: Name of PEXA subscriber involved in Property transaction
          type: string
        subscriberId:
          type: string
          description: Id of the mortgagee as listed in PEXA Exchange
        subscriberName:
          type: string
          description: Lender name - an entity that lends money to a borrower for the purpose of purchasing real estate. Normally it’s the bank. It is the name of the Mortgagee registered on parent title
    VicPropertyDetails:
      type: object
      description: Property details for the VIC jurisdiction
      required:
      - restrictiveCovenant
      properties:
        restrictiveCovenant:
          description: A restrictive covenant is a private treaty or written agreement between landowners that limits the way land can be used and developed
          type: boolean
        covenantMcpRef:
          type: string
          description: The covenant MCP reference
          maxLength: 150
        covenantMcpExpiryDate:
          type: string
          description: Some restrictive covenant have a lapse date or a date when they end. Most don't! That means the restriction apply to the land even if it's sold multiple times, the convenant will remain on title until it is removed.
          pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}$
        municipalityName:
          type: string
          description: Council name. For example - Bendigo council, Ballarat council etc
          pattern: Alpine Shire Council|Ararat Rural City Council|Ballarat City Council|Banyule City Council|Bass Coast Shire Council|Baw Baw Shire Council|Bayside City Council|Benalla Rural City Council|Boroondara City Council|Brimbank City Council|Buloke Shire Council|Campaspe Shire Council|Cardinia Shire Council|Casey City Council|Central Goldfield Shire Council|Colac Otway Shire Council|Corangamite Shire Council|Darebin City Council|East Gippsland Shire Council|Frankston City Council|French Island|Gannawarra Shire Council|Glen Eira City Council|Glenelg Shire Council|Golden Plains Shire Council|Greater Bendigo City Council|Greater Dandenong City Council|Greater Geelong City Council|Greater Shepparton City Council|Hepburn Shire Council|Hindmarsh Shire Council|Hobsons Bay City Council|Horsham Rural City Council|Hume City Council|Indigo Shire Council|Kingston City Council|Knox City Council|Latrobe City Council|Loddon Shire Council|Macedon Ranges Shire Council|Manningham City Council|Mansfield Shire Council|Maribyrnong City Council|Maroondah City Council|Melbourne City Council|Melton City Council|Mildura Rural City Council|Mitchell Shire Council|Moira Shire Council|Monash City Council|Moonee Valley City Council|Moorabool Shire Council|Merri-bek City Council|Mornington Peninsula Shire Council|Mount Alexander Shire Council|Moyne Shire Council|Murrindindi Shire Council|Nillumbik Shire Council|Northern Grampians Shire Council|Port Phillip City Council|Pyrenees Shire Council|Queenscliffe - Borough of|South Gippsland Shire Council|Southern Grampians Shire Council|Stonnington City Council|Strathbogie Shire Council|Surf Coast Shire Council|Swan Hill Rural City Council|Towong Shire Council|Wangaratta Rural City Council|Warrnambool City Council|Wellington Shire Council|West Wimmera Shire Council|Whitehorse City Council|Whittlesea City Council|Wodonga Rural City Council|Wyndham City Council|Yarra City Council|Yarra Ranges Shire Council|Yarriambiack Shire Council
        natureOfProperty:
          type: string
          description: Type of property. Example - Residential, Vacant land, Commercial etc
          pattern: Residential vacant land|Residential|Commercial|Industrial|Extractive industries|Primary production|Infrastructure|Community services|Sport
        primaryLandUse:
          $ref: '#/components/schemas/PrimaryLandUse'
        primaryConstructionType:
          $ref: '#/components/schemas/PrimaryConstructionType'
    Project:
      description: Object with all required details for a Project
      type: object
      required:
      - projectName
      - jurisdiction
      - workgroupId
      - parentTitle
      - supplierApplicable
      - withMortgageeOnTitles
      - intentionToLock
      - projectStages
      - settlementRestriction
      properties:
        projectName:
          type: string
          description: The Name of the project
          pattern: ^[\w\s\-!@#$%^&*()+={}\[\]|:;',.?/~`]+$
          maxLength: 150
        jurisdiction:
          $ref: '#/components/schemas/Jurisdiction'
        workgroupId:
          description: The Workgroup id that the project will belongs to
          type: integer
          format: int64
        estimatedSettlementDate:
          type: string
          description: The Estimated Settlement Date of the project
          format: string
        parentTitle:
          type: string
          description: The Parent Land Title
          format: string
          minLength: 1
        proprietorOnTitle:
          description: List of Proprietor(s) on Title
          type: array
          items:
            description: A proprietor on title
            type: string
        supplierApplicable:
          type: boolean
          description: Is the Supplier Details section mandatory?
        supplierDetails:
          $ref: '#/components/schemas/SupplierDetails'
        withMortgageeOnTitles:
          type: boolean
          description: Is there a mortgage registered on the title?
        mortgageeOnTitles:
          type: array
          items:
            $ref: '#/components/schemas/MotParticipants'
        intentionToLock:
          type: boolean
          description: Do you intend to restrict account(s) this project can disburse to?
          example: true
        projectStages:
          type: boolean
          description: Do you intend to have more than one stage to this project?
          example: false
        settlementRestriction:
          type: boolean
          description: Do you intend to restrict Incoming Proprietor Representative(s) from proposing the settlement date?
          example: true
        nswPropertyDetails:
          $ref: '#/components/schemas/NswPropertyDetails'
        qldPropertyDetails:
          $ref: '#/components/schemas/QldPropertyDetails'
        vicPropertyDetails:
          $ref: '#/components/schemas/VicPropertyDetails'
        id:
          readOnly: true
          type: integer
          format: int64
          description: The id of the project
        projectStatus:
          readOnly: true
          type: string
          description: The project status
        historicalParentTitles:
          readOnly: true
          type: array
          description: All historical parent titles of project
          items:
            description: A historical parent title
            type: string
        workspacesCreated:
          readOnly: true
          type: boolean
          description: If workspaces have been created for this project
    ProjectStatus:
      type: object
      description: Status details of a project
      properties:
        jurisdiction:
          $ref: '#/components/schemas/Jurisdiction'
        proprietorOnTitles:
          description: List of Proprietor(s) on Title
          type: array
          items:
            description: A proprietor on title
            type: string
        parentTitle:
          type: string
          description: The Parent Land Title
          format: string
        mortgageeNames:
          description: List of Mortgagee(s) on Title
          type: array
          items:
            description: A mortgagee on title
            type: string
        estimatedSettlementDate:
          type: string
          description: The Estimated Settlement Date of the project
          format: string
        invitationAcceptance:
          type: object
          description: The status of invitation acceptance
          properties:
            incomingMortgagee:
              $ref: '#/components/schemas/InvitationAcceptanceStatus'
            mortgageeOnTitle:
              $ref: '#/components/schemas/InvitationAcceptanceStatus'
            incomingProprietor:
              $ref: '#/components/schemas/InvitationAcceptanceStatus'
        settlementDateAcceptance:
          type: object
          description: The status of settlement date acceptance
          properties:
            incomingMortgagee:
              $ref: '#/components/schemas/SettlementDateAcceptanceStatus'
            mortgageeOnTitle:
              $ref: '#/components/schemas/SettlementDateAcceptanceStatus'
            incomingProprietor:
              $ref: '#/components/schemas/SettlementDateAcceptanceStatus'
        workspaceStatus:
          $ref: '#/components/schemas/WorkspaceCountsByStatuses'
    CurrentLandUse:
      type: string
      description: Current land use
      pattern: Vacant Land|Dwelling|Multi Unit|Flats|Guest House Private Hotel|Farming|Industrial|Commercial|Other
    SmokeAlarm:
      type: object
      description: Smoke alarm are the devices that are able to detect smoke in the event of a fire and sound an alarm to alert people to the potential danger. In QLD, it's a legal requirement that the seller is required to complete prior to the buyer signing the contract, stating whether the property is fitted with compliant smoke alarms
      properties:
        installed:
          type: boolean
          description: Compliant smoke alarm/s installed
        informed:
          type: boolean
          description: Transferee has been informed in writing about its existence
    Error:
      description: Error related to the API
      type: object
      properties:
        code:
          description: Error code
          type: string
          example: OB0001.000
        message:
          description: Error message
          type: string
          example: The request is invalid
        details:
          description: Optional list of error details
          type: array
          items:
            type: string
            description: Error details
    ParticipantSettlementDateStatus:
      type: string
      description: 'The status of settlement date acceptance by a participant. Can be one of the following: * ACCEPTED - Accepted * PENDING - Awaiting Response

        '
      format: string
    SettlementDateStatus:
      type: string
      description: 'The overall status of settlement date acceptance. Can be one of the following: * ACCEPTED - All Accepted * PARTIALLY_ACCEPTED - Pending others * PENDING - Pending * NO_ACCEPTANCE - No acceptance

        '
      format: string
    SafetySwitch:
      type: object
      description: A safety switch is a device that quickly switches off the electric supply if an  electric fault is detected, to minimise the risk of electricity -related fires, electric shock, injury to death. In QLD, it's a legal requirement for all properties to have an electrical safety switch installed. When selling your property you must disclose whether a safety switch is installed in the property on the contract of sale, as well as on the property transfer document
      properties:
        installed:
          type: boolean
          description: Electrical safety switch installed
        informed:
          type: boolean
          description: Transferee has been informed in writing about its existence
    WorkspaceCountsByStatuses:
      type: object
      description: Counts for various properties of workspaces under the project
      properties:
        allActive:
          description: Count of all active workspaces
          type: integer
          format: int64
        settlingToday:
          description: Count of workspaces settling today
          type: integer
          format: int64
        completed:
          description: Count of completed workspaces
          type: integer
          format: int64
        withdrawn:
          description: Count of withdrawn workspaces
          type: integer
          format: int64
        all:
          description: Count of workspaces
          type: integer
          format: int64
        awaitingDigitalSignature:
          description: Count of workspaces that are awaiting digital signatures
          type: integer
          format: int64
    Errors:
      description: List of errors related to the API
      type: object
      properties:
        exceptionList:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Error'
    PrimaryConstructionType:
      type: string
      description: Material used to construct the property. Example - Timber, Brick etc
      pattern: Not applicable|Brick|Brick Veneer|Fibro|Timber|OTHER
    QldPropertyDetails:
      type: object
      description: Property details for the QLD jurisdiction
      properties:
        currentLandUse:
          $ref: '#/components/schemas/CurrentLandUse'
        marginScheme:
          type: boolean
          description: Is the transaction under the margin scheme?
        safetySwitch:
          $ref: '#/components/schemas/SafetySwitch'
        smokeAlarm:
          $ref: '#/components/schemas/SmokeAlarm'
    ProjectsWorkspace:
      type: object
      description: Details of a workspace
      properties:
        workspaceId:
          type: string
          description: The id of the workspace
          format: string
        subscriberReference:
          type: string
          description: The subscriber reference
          format: string
        unregisteredLotNumbers:
          type: array
          description: The lot numbers on unregistered plan
          items:
            description: An unregistered lot number
            type: string
        childTitles:
          type: array
          description: The list of child titles
          items:
            description: A child title
            type: string
        participantRepresentativeData:
          type: object
          description: The details of the participant representatives
          properties:
            incomingMortgagee:
              type: array
              description: The list of participant representatives for incoming mortgagee
              items:
                description: The name of a participant representative for incoming mortgagee
                type: string
            mortgageeOnTitle:
              type: array
              description: The list of participant representatives for mortgagee on title
              items:
                description: The name of a participant representative for mortgagee on title
                type: string
            incomingProprietor:
              type: array
              description: The list of participant representatives for incoming proprietor
              items:
                description: The name of a participant representative for incoming proprietor
                type: string
            proprietorOnTitle:
              type: array
              description: The list of participant representatives for proprietor on title
              items:
                description: The name of a participant representative for proprietors on title
                type: string
        unrepresentedPartyData:
          type: object
          description: The details of the unrepresented parties
          properties:
            incomingMortgagee:
              type: array
              description: The list of unrepresented parties for incoming mortgagee
              items:
                description: The name of an unrepresented party for incoming mortgagee
                type: string
            mortgageeOnTitle:
              type: array
              description: The list of unrepresented parties for mortgagee on title
              items:
                description: The name of an unrepresented party for mortgagee on title
                type: string
            incomingProprietor:
              type: array
              description: The list of unrepresented parties for incoming proprietor
              items:
                description: The name of an unrepresented party for incoming proprietor
                type: string
            proprietorOnTitle:
              type: array
              description: The list of unrepresented parties for proprietor on title
              items:
                description: The name of an unrepresented party for proprietors on title
                type: string
        lodgementStatus:
          type: string
          description: The lodgement status
          format: string
        settlementStatus:
          type: string
          description: The settlement status
          format: string
        settlementDate:
          type: string
          description: 'The settlement date (format: YYYY-MM-DD, for example, 2023-01-25)'
          format: date
        settlementDateAcceptance:
          type: object
          description: The status of settlement date acceptance
          properties:
            status:
              $ref: '#/components/schemas/SettlementDateStatus'
            statusDetails:
              type: object
              description: The status of settlement date acceptance by participants
              properties:
                acceptanceByIncomingMortgageeReps:
                  $ref: '#/components/schemas/ParticipantSettlementDateStatus'
                acceptanceByMortgageeOnTitleReps:
                  $ref: '#/components/schemas/ParticipantSettlementDateStatus'
                acceptanceByIncomingProprietorReps:
                  $ref: '#/components/schemas/ParticipantSettlementDateStatus'
        financialData:
          type: object
          description: The financial details of the workspace
          properties:
            gstWithholdingStatus:
              $ref: '#/components/schemas/GstWithholdingStatus'
            grossConsideration:
              type: string
              description: The gross consideration amount
              format: string
            vendorFunds:
              type: string
              description: The vendor funds amount
              format: string
            payoutAmount:
              type: string
              description: The payout amount
              format: string
            balanced:
              type: boolean
              description: Whether the workspace is balanced
    SettlementDateAcceptanceStatus:
      description: Counts for settlement date acceptance
      type: object
      properties:
        accepted:
          description: Count of settlement dates that are accepted
          type: integer
          format: int64
        pending:
          description: Count of settlement dates that are pending
          type: integer
          format: int64
    SupplierDetails:
      type: object
      description: Details for the supplier
      required:
      - name
      - phone
      - abn
      - addressLine1
      - suburb
      - postcode
      - state
      - email
      properties:
        name:
          type: string
          description: Supplier's name
          pattern: ^[a-zA-Z0-9\s-`!@#$&(){}_=\\\[\]|;:',.?\/"]+$
          maxLength: 200
        phone:
          type: string
          description: Supplier's phone number
          pattern: ^[0-9]+$
          maxLength: 19
        abn:
          type: string
          description: Supplier's ABN containing 11 digits
          pattern: ^(?:\s*\d\s*){11}$
        addressLine1:
          description: Supplier's first address line
          type: string
          pattern: ^[a-zA-Z0-9\s()&'/-]+$
          maxLength: 38
        addressLine2:
          type: string
          description: Supplier's second address line
          pattern: ^[a-zA-Z0-9\s()&'/-]+$
          maxLength: 38
        suburb:
          type: string
          description: Supplier's suburb
          pattern: ^[a-zA-Z0-9\s()&'/-]+$
          maxLength: 46
        postcode:
          type: string
          description: Supplier's postcode
          pattern: ^[0-9]{4}$
          maxLength: 4
        state:
          $ref: '#/components/schemas/Jurisdiction'
        email:
          type: string
          description: Supplier's email address
          pattern: ^[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?
          maxLength: 200
    InvitationAcceptanceStatus:
      type: object
      description: Counts of the various statuses for an invitation
      properties:
        accepted:
          description: Count of accepted invitations
          type: integer
          format: int64
        pending:
          description: Count of pending invitations
          type: integer
          format: int64
        declined:
          description: Count of declined invitations
          type: integer
          format: int64
        notInvited:
          description: Count of invitations that have not been sent
          type: integer
          format: int64
    Jurisdiction:
      type: string
      description: Jurisdiction
      pattern: ACT|NSW|VIC|WA|QLD|SA|TAS
    PrimaryLandUse:
      type: string
      description: For which purpose the land will be used for. Example - dwelling, carpark, flat multi-storey etc
  responses:
    ErrorResponse:
      description: Error Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  parameters:
    RequestCorrelationIdHeader:
      description: A unique request id provided by api caller to support end-to-end troubleshooting and tracing
      in: header
      name: X-Request-Correlation-Id
      schema:
        type: string
        format: UUID
        example: 123e4567-e89b-12d3-a456-426614174000
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://host.kubernetes.internal/auth/realms/pexa/protocol/openid-connect/auth
          tokenUrl: https://host.kubernetes.internal/auth/realms/pexa/protocol/openid-connect/token
          scopes:
            au:projects:project:write: Grant project write access
            au:projects:status:read: Grant project status read access
            au:projects:workspaces:read: Grant project workspaces read access
        clientCredentials:
          tokenUrl: https://host.kubernetes.internal/auth/realms/pexa/protocol/openid-connect/token
          scopes:
            au:projects:project:write: Grant project write access
            au:projects:status:read: Grant project status read access
            au:projects:workspaces:read: Grant project workspaces read access
x-idp-config:
  consumer-claim: azp
  scopes-claim: scope
x-disable-subscription: 'off'
x-protected-view: 'off'
x-rate-limits:
  limit: 200
  window_size: 60
  window_type: sliding
x-service-limits:
  limit: 200
  window_size: 60
  window_type: sliding
x-apim-hosts:
- '{{ host }}'
